name: Init

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ROOT_DIRECTORY: ${{ github.workspace }}
    if: ${{ contains(github.event.head_commit.message, 'Initial commit') }}

    steps:
      - uses: actions/checkout@v2

      - name: Set Domain Name
        run: |
          echo "DOMAIN_NAME=$(echo ${{ github.event.repository.name }} | cut -d '-' -f3)" >> $GITHUB_ENV
          echo "DOMAIN_NAME_UPPER_CASE=$(echo ${{ github.event.repository.name }} | cut -d '-' -f3 | sed -e "s/\b\(.\)/\u\1/g" )" >> $GITHUB_ENV
        

      - name: Rename File
        run: |
          sed -i 's/V1ServiceApplication/V1Service${{ env.DOMAIN_NAME_UPPER_CASE }}Application/g' ${{ env.ROOT_DIRECTORY }}/infrastructure/src/main/java/io/github/v1service/V1ServiceApplication.java
          mv ${{ env.ROOT_DIRECTORY }}/infrastructure/src/main/java/io/github/v1service/V1ServiceApplication.java ${{ env.ROOT_DIRECTORY }}/infrastructure/src/main/java/io/github/v1service/V1Service${{ env.DOMAIN_NAME_UPPER_CASE }}Application.java
          mv ${{ env.ROOT_DIRECTORY }}/domain/src/main/java/io/github/v1service ${{ env.ROOT_DIRECTORY }}/domain/src/main/java/io/github/v1service${{ env.DOMAIN_NAME }} 
          mv ${{ env.ROOT_DIRECTORY }}/domain ${{ env.ROOT_DIRECTORY }}/${{ env.DOMAIN_NAME }}-domain         
          mv ${{ env.ROOT_DIRECTORY }}/infrastructure/src/main/java/io/github/v1service ${{ env.ROOT_DIRECTORY }}/infrastructure/src/main/java/io/github/v1service${{ env.DOMAIN_NAME }}
          mv ${{ env.ROOT_DIRECTORY }}/infrastructure ${{ env.ROOT_DIRECTORY }}/${{ env.DOMAIN_NAME }}-infrastructure 

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: parksangwoo1617
          author_email: b01056721617@gmail.com
          message: 'Rename Files'
          add: '.'
